### ISSUE TITLE
setup tree cannot find tree modulepath

### ISSUE THREAD

**Issue by joelbrownstein** [sdss/tree#10]
https://github.com/sdss/tree/blob/0f8fd6466d061d9533f3602e34f34f4378bdb3b4/bin/setup_tree.py#L359

The return statement causes the loop to terminate after the first modulepath, so it never gets to the modulepath containing tree.

**Comment by havok2063** [comment]
@joelbrownstein I think I fixed this.  Can you please update the `master` tree and try again?

**Comment by havok2063** [comment]
This has been fixed.
