### ISSUE TITLE
astra IPL directories mismatched with paths

### ISSUE THREAD

**Issue by havok2063** [sdss/tree#48]
Hi @andycasey ,  @joelbrownstein and I noticed the astra path contents for IPL-1 are incorrect compared to sdss5, making the sdss_access path definitions and datamodel incorrect.   It looks like the IPL-1 paths are missing the two top level versions, [https://data.sdss5.org/sas/ipl-1/spectro/astra/](https://data.sdss5.org/sas/ipl-1/spectro/astra/ ), as seen in sdss5, [https://data.sdss5.org/sas/sdsswork/mwm/spectro/astra/0.2.6/v6_0_9-1.0/](https://data.sdss5.org/sas/sdsswork/mwm/spectro/astra/0.2.6/v6_0_9-1.0/).  An example broken IPL-1 path is `mwmStar = $MWM_ASTRA/{v_astra}/{run2d}-{apred}/spectra/star/@cat_id_groups|/mwmStar-{v_astra}-{cat_id}@component_default|.fits
`

Was there a reason you moved the contents up two levels or was this unintentional?   I think we have a few options. 

1. Leave the IPL-1 content on disk as is, and update the IPL-1 path and datamodel definitions to reflect this.
2. Move the content back under the `0.2.6/v6_0_9-1.0/` directories.  The paths and datamodels would need no changes.
3. Create a new `0.2.6/v6_0_9-1.0/` directory that symlinks over into the existing content.  This accommodates the announced release but is a bit clunky.  

Personally I think the version information should remain in the directory path, so I would vote for option 2.    If you have time, Joel and I are happy to chat in person with you about this as well.

**Comment by andycasey** [comment]
This was unintentional... I was very sleep deprived at the time!

I would vote for option 2 *after* this week.

**Comment by havok2063** [comment]
This has been resolved.
