### ISSUE TITLE
make module dependencies optional

### ISSUE THREAD

**Issue by joelbrownstein** [sdss/tree#50]
Hi @havok2063 

I ran some tests installing the SDSS software framework via pip install sdss-access which then installs sdss-tree, and sdsstools (without modules).  I then ran setup_tree.py by following https://sdss-tree.readthedocs.io/en/latest/tree_setup.html#creating-environment-symlinks.  This worked great, except the resulting modulefiles include module load dependencies for sdsstools and sdss_access, which is broken since those dependencies were pip installed and do not have modulefiles, and if they did the pythonpath would over-ride the pip installed paths, so this usecase is broken.

Can we remove the module file dependencies so that tree does not look for module files for sdss_access or sdsstools or do you have another way to fix this?

Thanks,
Joel

**Comment by havok2063** [comment]
@joelbrownstein  I think you're technically mixing installation methods.  You can try to install tree following https://wiki.sdss.org/display/DATA/tree#tree-InstallationofthetreeproductatUtah.   I think the `setup_tree.py` was originally designed to be used with git cloning the repo, and separately installing modules for `sdsstools` and `sdss_access`. 

However, I think you bring up some good points about installation steps.  I think I can make those module prereqs optional during setup to help make your install workflow work.  If I understand correctly, basically we want those prereqs to exist when tree is git cloned but not when tree is pip installed.  With a check that `sdsstools` and `sdss_access` are pip installed already.

**Comment by havok2063** [comment]
Ahh I see, that makes sense.  I think #51 should resolve your issue.

**Comment by joelbrownstein** [comment]
Perfect!  Thanks!
