### ISSUE TITLE
Installing 4.0.2 error

### ISSUE THREAD

**Issue by joelbrownstein** [sdss/tree#63]
Hi @havok2063 

Looks like some vestigial code is is causing an issue at setup_tree.py line 470 with the create symlink sdsswork -> sdss5 command.  Can we just remove that out and retag 4.0.2?

```
SETUP> tree/4.0.2 using /uufs/chpc.utah.edu/common/home/sdss10/software/sdss/github/tree/4.0.2
SETUP> Using miniconda/3.11
PYTHON> setup_tree -> /uufs/chpc.utah.edu/common/home/sdss50/software/modulefiles/tree
Enter a path for SAS_BASE_DIR: /uufs/chpc.utah.edu/common/home/sdss50
Environment files created in: /uufs/chpc.utah.edu/common/home/sdssunit/.tree/environments
Copying module files...
[ERROR]: Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/sdss10/software/sdss/github/tree/4.0.2/bin/setup_tree.py", line 585, in <module>
    main(opts)
  File "/uufs/chpc.utah.edu/common/home/sdss10/software/sdss/github/tree/4.0.2/bin/setup_tree.py", line 578, in main
    copy_modules(filespath=etcdir, modules_path=opts.modulesdir, verbose=opts.verbose, default=opts.default, force=opts.force)
  File "/uufs/chpc.utah.edu/common/home/sdss10/software/sdss/github/tree/4.0.2/bin/setup_tree.py", line 470, in copy_modules
    os.symlink('sdsswork', path5)
FileExistsError: [Errno 17] File exists: 'sdsswork' -> '/uufs/chpc.utah.edu/common/home/sdss50/software/modulefiles/tree/sdss5'

```

**Comment by havok2063** [comment]
@joelbrownstein I can't reproduce this error.  I think this is just a temporary artifact of the transition from the old tree to the new tree.  You should remove the physical `sdss5` module file and re-run the setup.  I can add a check to the following to delete the physical file first. 
```
    # create a symlink from sdsswork to sdss5
    path5 = os.path.join(tree_mod, 'sdss5')
    if os.path.islink(path5):
        os.unlink(path5)
    os.symlink('sdsswork', path5)
```

**Comment by joelbrownstein** [comment]
There is no link to be removed.  I tried again with modulefiles/tree renamed to get it out of the way and the same error occurred.  However I was able to install from main (4.0.2-4-ga326e73), just not the tag 4.0.2, so we can close this issue, and I'll just use main in future.

**Comment by joelbrownstein** [comment]
spoke too soon.  the output of the setup_tree command (no crash from bad link) is here: /uufs/chpc.utah.edu/common/home/sdss50/software/modulefiles/tree and includes mpls ?

**Comment by joelbrownstein** [comment]
I have the answer, just not sure how to fix it.

The problem occurs when the miniconda I'm using (since I need some miniconda) has tree pip installed.

$ ipython
Python 3.11.3 | packaged by conda-forge | (main, Apr  6 2023, 08:57:19) [GCC 11.3.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.12.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import tree

In [2]: tree.__version__
Out[2]: '3.1.6'
