### ISSUE TITLE
clean break for IPL3

### ISSUE THREAD

**Issue by ajwheeler** [sdss/tree#65]
There are several astra files that existed in either IPL-1 or IPL-2 that don't exist any more, either because temporary names were changed to something better or because an astra pipeline was dropped.  For IPL-3 should we create a non-inheriting release and add everything anew?

I'm going to add a bunch of apogee reduction files to the datamodel soon, and some of them aren't yet in tree, so it would be helpful to add an IPL-3 release now.

**Comment by joelbrownstein** [comment]
We won't add ipl3.cfg to tree until IPL3 exists on the SAS, so please use sdssword.cfg in the meantime.  However when it is needed, we would not make it non-inheriting since any paths that changed since ipl1/ipl2 would simply be included in ipl3.cfg which would over-ride the inheritance for that file path.

**Comment by ajwheeler** [comment]
Got it, thanks!

The reason to do a non-inheriting release (at some point) would be that
there are species/prefixes that were introduced in IPL1 and IPL2 which no
longer exist. If that’s not a problem, it’s not a problem for me, but I
just wanted to make sure.

**Comment by havok2063** [comment]
Although mildly annoying I don't think it's too terrible to have deprecated species carried along.  If you want to create a brand new config for IPL-3, that's ok, but all previous content  that are preserved  (i.e. sections, envvars, paths) from both IPL-1 and IPL-2 configs will need to be copied over.  IPL-3 would then become the new base for all future IPLs.

**Comment by ajwheeler** [comment]
I’m fine with both approaches. If forced to choose, I would say that it’s
ok to keep the vestigial species. I just wanted to make sure we are all on
the same page.

**Comment by havok2063** [comment]
I think this can be closed.
